require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Rails: true
  Exclude:
    - bin/*
    - node_modules/**/**/**/**/*
    - vendor/bundle/**/*
    - db/**/*
Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/*
Style/Encoding:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - app/admin/*
    - spec/**/*
    - config/environments/*
    - config/initializers/*
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 10